FROM node:20-alpine

# Install OpenSSL (required by Prisma)
RUN apk add --no-cache openssl openssl-dev libc6-compat

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy prisma schema
COPY prisma ./prisma

# Generate Prisma client
RUN npx prisma generate

# Copy source
COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]